import { Inter } from "next/font/google";
import "./globals.css";
import HouseContextProvider from "@/components/Search/houseContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <HouseContextProvider>
      <html lang='pt'>
      <link
        rel='shortcut icon'
        href='/Moraes/favicon.jpg'
        type='image'
        className='rounded-lg'
      />
      
      <body className='relative dark:bg-slate-900'>
       
        {children}
      </body>
      
    </html>
    </HouseContextProvider>
  );
}
